language: node_js
node_js:
  - 8.9.3
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm run develop
script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_success:
  - cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js