language: node_js
node_js:
  - 8.9.3
cache:
  directories:
    - node_modules
install:
  - npm run develop
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test
